### PR TITLE
[fix] pyproject.toml: fix [tool.poetry]packages definition

### PR DESCRIPTION
**Pull request by return42**
The `from` value needs to be set in the package definition[1].

[1] https://python-poetry.org/docs/pyproject/#packages

Signed-off-by: Markus Heiser <markus.heiser@darmarit.de>

### CODE REVIEW

**Comment by tardyp** [comment]
you should update the poetry.lock by just 'running poetry update'

The test are failing, it looks like there is an import error. I think there must be an import error because we are using an old api of docutils

**Comment by return42** [comment]
I am a bit confused .. the tests of [cbde81f](https://github.com/tardyp/sphinx-jinja/pull/32/commits/cbde81f31bf1e5a0f9e91343809d45813cb0e7a9) are passed without an issue:

https://github.com/tardyp/sphinx-jinja/runs/5464383328?check_suite_focus=true

**Comment by return42** [comment]
I assume poetry is broken / or I do not understand how it works.#

By example:

```
$ python3 -m venv  local
$ . ./local/bin/activate
(local)$ pip install poetry
(local)$ poetry update      # does not change anything
(local)$ poetry install
...
Installing the current project: sphinx-jinja (1.4.1)
```

But the module `jinja.py` is not installed in `sphinxcontrib`:

```
(local)$ ls local/lib/python3.8/site-packages/sphinxcontrib
applehelp  devhelp  htmlhelp  jsmath  qthelp  serializinghtml
```

And here is a installation with pip:

```
(local)$ pip install .
...
Successfully installed sphinx-jinja-1.4.1
```

And now `jinja.py` is really installed in `sphinxcontrib` ...

```
(local)$ ls local/lib/python3.8/site-packages/sphinxcontrib
applehelp  devhelp  htmlhelp  __init__.py  jinja.py  jsmath  __pycache__  qthelp  serializinghtml
```

I don't have a clue whats going wrong with poetry / sorry, I can't help with poetry

**Comment by tardyp** [comment]
the problem is not with poetry. if you install docutils 0.16 back then the tests pass..

**Comment by tardyp** [comment]
```
poetry run pip install docutils==0.16
Collecting docutils==0.16
  Downloading docutils-0.16-py2.py3-none-any.whl (548 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 548.2/548.2 KB 5.0 MB/s eta 0:00:00
Installing collected packages: docutils
  Attempting uninstall: docutils
    Found existing installation: docutils 0.17.1
    Uninstalling docutils-0.17.1:
      Successfully uninstalled docutils-0.17.1
Successfully installed docutils-0.16
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
0 % poetry run pytest
============================================================================================================================ test session starts =============================================================================================================================
platform darwin -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
collected 7 items

tests/test_basic.py .......
============================================================================================================================= 7 passed in 1.66s ==============================================================================================================================
```

**Comment by tardyp** [comment]
I think the new docutil somehow do not want us to be in sphinxcontrib anymore.

If I rename the package, then it works better.

https://github.com/tardyp/sphinx-jinja/pull/33

**Comment by tardyp** [comment]
fixed merge and new version released

**Comment by return42** [comment]
> the problem is not with poetry.

Very strange .. why does poetry not report an error when it does not install or can not install `sphinxcontrib.jinja` .. and why does the installation using pip do work? --> https://github.com/tardyp/sphinx-jinja/pull/32#issuecomment-1062138352

Anyway, thanks for fixing the issue!

**Pull request closed without merging**
